---
:name: Twitter
:slug: twitter
:description: mikutterにTwitter連携機能を追加するプラグインです。
:depends:
  :mikutter: '3.6'
  :plugin:
  - score
  - skin
  - spell
  - twitter_api_keys
  - world
:version: '1.1'
:author: toshi_a
